// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spoookrrsotlksmptmry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwb29va3Jyc290bGtzbXB0bXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzAwNDksImV4cCI6MjA2MjU0NjA0OX0.vMmYRdE7L8_009d-bGjLt393QrzvKmbIZGHSsXk7ObU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);