// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abqfwunvsujkiijeqzsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFicWZ3dW52c3Vqa2lpamVxenNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzQ4ODQsImV4cCI6MjA2MjU1MDg4NH0.VX5tfepfURFOMbwkecbi-V1weCXR0dMi2dxECQgIBG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);